// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz89MBNIVnI5LD5z3K7h8f_9yNwbzLwU4',
    appId: '1:773067738112:web:3e8f3de4acbb33d2851ce5',
    messagingSenderId: '773067738112',
    projectId: 'sport-a5627',
    authDomain: 'sport-a5627.firebaseapp.com',
    storageBucket: 'sport-a5627.appspot.com',
    measurementId: 'G-EMG2ZW2Y9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzPY9Z2gYqYh7rRaDCSf5C8kV1Miic0ZI',
    appId: '1:773067738112:android:2f84f6cbd1e52c62851ce5',
    messagingSenderId: '773067738112',
    projectId: 'sport-a5627',
    storageBucket: 'sport-a5627.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXTihRZf-JepzoNzah1Dkaah6Koky3rDU',
    appId: '1:773067738112:ios:90ac726f493b7780851ce5',
    messagingSenderId: '773067738112',
    projectId: 'sport-a5627',
    storageBucket: 'sport-a5627.appspot.com',
    iosClientId: '773067738112-ib4h2adtqdiqgssecionqr9d1or7ea00.apps.googleusercontent.com',
    iosBundleId: 'com.example.sport_execute',
  );
}
